### ISSUE TITLE
Could't load the app

### ISSUE THREAD

**Issue by keccah** [yonicd/Elections#4]
Hey, nice work. But I can't open the app. I'm working on a mac. 

I get the message "Error in as.POSIXct.default(time2)" when trying to open the app. What can I be doing wrong? 

I was willing to see if I could use your thoughts to work with elections in Brazil =P 

Thanks

**Comment by yonicd** [comment]
Hi

are you running it locally on your computer?

**Comment by yonicd** [comment]
My guess would be that you need to change from windows to mac in the first line

``` r
if (Sys.info()[1] == "Windows") Sys.setlocale("LC_TIME","C") 
```

check what it `Sys.info()[1]` returns for you on you system

**Comment by yonicd** [comment]
I changed the github version to static delegate count data. Working with Rselenium and phantomjs is not for everyone. 

The app should work now without a problem running it directly form github.

The elections in Brazil should be really interesting :)

yoni
